version: '3.9'
services:
  server:
    build: .
    ports:
      - '5000:5000'
    # environment:
    #   PORT: 5001
    #   DB_HOST: db
    #   DB_PORT: 5432
    #   NODE_ENV: production
    depends_on:
      - db
  db:
    container_name: testTaskDB
    image: 'postgres'
    ports:
      - '5444:5432'
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=docker
    volumes:
      - ./data/postgres:/var/lib/postgresql/data